### ISSUE TITLE
Missing Details.

### ISSUE THREAD

**Issue by Crystal-Chaos** [Leather128/LeatherEngineGodot#14]
Pixelated Death Animation + Music and Sound Effects.
Pixelated Countdown Sound Effects.
Game-Over Camera Wrong-Positioning After Dying Right Away.
Dialogue System showing up in an instant, the effect appears rather late and the text box animation keeps on playing instead of staying in the final spriteframe when procceding to the next dialogue.

**Comment by Mariogamerexpert** [comment]
If you couldn't tell, this is being built from the ground up. So, in its current state, yes it's going to have some stuff missing. Leather moved on to developing the (hopefully) successor to Leather Engine anyway, so LE Godot might get archived just like the original LE did. Might as well compile the code for Fabric Engine and see what it has to offer so far. From what I heard, not even hold notes have been implemented yet, so don't expect much.

**Comment by Leather128** [comment]
lol fabric has sustains by now!!!!!!

**Comment by Leather128** [comment]
(also i've decided to kinda work on leather haxe, leather godot, and fabric whenever i want instead of sticking to one project as my motivation is wacky)
